<article>
    <header class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </header>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
        <p>
            <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
            <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
        </p>
        <p class="required"><small><?php echo $this->__('* Required Fields') ?></small></p>
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>">&laquo; <?php echo $this->__('Back to Login') ?></a></p>
        
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
    </form>
</article>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>