<article class="block-content">
    <header class="page-title">
        <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
    </header>
    <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
        <p>
            <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
            <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" />
        </p>
        <p>
            <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
        </p>
        <p>
            <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
            <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;"/>
        </p>
        <p>
            <label class="required"><?php echo Mage::helper('sales')->__('Find Order By') ?></label>
            <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                <option value="email"><?php echo Mage::helper('sales')->__('Email Address') ?></option>
                <option value="zip"><?php echo Mage::helper('sales')->__('ZIP Code') ?></option>
            </select>
        </p>
        <p id="oar-email">
            <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
            <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email" />
        </p>
        <p id="oar-zip">
            <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
            <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" />
        </p>
        <p class="required"><small><?php echo $this->__('* Required Fields') ?></small></p>
        <p>
            <button type="submit" title="Continue" class="button"><?php echo Mage::helper('sales')->__('Continue') ?></button>
        </p>
    </form>
</article>
<script>
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>