<?php
/**
 * Product list template (forced grid)
 *
 * @see Mage_Catalog_Block_Product_List
 */

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

    <div class="category-products">

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>

            <?php echo $i++%$_columnCount==0 ? '<ul class="products-grid">' : ''; ?>

                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(176); ?>" width="176" height="176" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>

                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

                    <?php echo $this->getPriceHtml($_product, true) ?>
                </li>

            <?php echo $i%$_columnCount==0 || $i==$_collectionSize? '</ul>' : ''; ?>

        <?php endforeach ?>

    </div>
    <script>decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

<?php endif; ?>