<?php echo $this->getChildHtml('head') ?>
<body<?php echo $this->getBodyClass()?' class="col1-layout'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <?php echo $this->getChildHtml('global_messages') ?>
    <div id="content">
        <div class="col-main" role="main">
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>